In [2]:
import torch
print(torch.__version__)

1.13.0


## Функции активации и функции потерь

In [3]:
# Функции активации
vec = torch.tensor([1., -0.5, 3., -2.])

print(
    f"Оригинальный тензор:\n{vec}",
    f"sigmoid:\n{torch.sigmoid(vec)}",
    f"tanh:\n{torch.tanh(vec)}",
    f"relu:\n{torch.relu(vec)}",
    f"softmax:\n{torch.softmax(vec, 0)}",
    f"log_softmax:\n{torch.log_softmax(vec, 0)}",
    sep="\n\n",
)

Оригинальный тензор:
tensor([ 1.0000, -0.5000,  3.0000, -2.0000])

sigmoid:
tensor([0.7311, 0.3775, 0.9526, 0.1192])

tanh:
tensor([ 0.7616, -0.4621,  0.9951, -0.9640])

relu:
tensor([1., 0., 3., 0.])

softmax:
tensor([0.1154, 0.0258, 0.8530, 0.0057])

log_softmax:
tensor([-2.1589, -3.6589, -0.1589, -5.1589])


In [4]:
# Функции потерь
y_true_reg = torch.tensor([1., -1., 2.])  
y_pred_reg = torch.tensor([0.8, -0.2, 2.5])

y_true_clf_class = torch.tensor([0, 2, 1])
y_true_clf_probs = torch.tensor([
    [1., 0., 0.],
    [0., 0., 1.],
    [0., 1., 0.],
])
y_pred_clf_log_probs = torch.tensor([
    [0.8, 0.1, 0.1],
    [0.4, 0.1, 0.5],
    [0., 0.98, 0.02],
]).log()
y_pred_clf_scores = torch.tensor([
    [10., 1., -2.5],
    [8., 2., 10.],
    [0., 28., 1.],
])

mse_loss_func = torch.nn.MSELoss()
ce_loss_func = torch.nn.CrossEntropyLoss()
nll_loss_func = torch.nn.NLLLoss()

print(
    f"MSE:\n{mse_loss_func(y_pred_reg, y_true_reg)}",
    f"CE с target классами:\n{ce_loss_func(y_pred_clf_scores, y_true_clf_class)}",
    f"CE с target вероятностями классов:\n{ce_loss_func(y_pred_clf_scores, y_true_clf_probs)}",
    f"NLL с target классами (target вероятностями NLL не умеет):\n{nll_loss_func(y_pred_clf_log_probs, y_true_clf_class)}",
    sep="\n\n",
)

MSE:
0.3100000321865082

CE с target классами:
0.042450178414583206

CE с target вероятностями классов:
0.042450178414583206

NLL с target классами (target вероятностями NLL не умеет):
0.31216445565223694
