In [1]:
import torch
print(torch.__version__)

1.13.1


## Вектора и матрицы в PyTorch

### 1. Что такое тензоры

In [2]:
vector = [1., 0.5, 3.7, -0.5]  # Создаём массив
matrix = [[1, 2], [3, 4]]  # И массив массивов

In [3]:
vector_tensor = torch.tensor(vector)  # Превращаем массив в одномерный тензор (вектор)
matrix_tensor = torch.tensor(matrix)  # Превращаем массив массивов в двумерный тензор (матрицу)

In [4]:
print(
    f"Вектор:\n{vector_tensor}",
    f"Размеры вектора                --> {vector_tensor.shape}",
    f"Количество размерностей        --> {vector_tensor.dim()}",
    f"Суммарное количество элементов --> {vector_tensor.numel()}",
    f"Какого типа элементы вектора   --> {vector_tensor.dtype}",
    sep="\n\n",
)

Вектор:
tensor([ 1.0000,  0.5000,  3.7000, -0.5000])

Размеры вектора                --> torch.Size([4])

Количество размерностей        --> 1

Суммарное количество элементов --> 4

Какого типа элементы вектора   --> torch.float32


In [5]:
print(
    f"Матрица:\n{matrix_tensor}",
    f"Размеры матрицы                --> {matrix_tensor.shape}",
    f"Количество размерностей        --> {matrix_tensor.dim()}",
    f"Суммарное количество элементов --> {matrix_tensor.numel()}",
    f"Какого типа элементы матрицы   --> {matrix_tensor.dtype}",
    sep="\n\n",
)

Матрица:
tensor([[1, 2],
        [3, 4]])

Размеры матрицы                --> torch.Size([2, 2])

Количество размерностей        --> 2

Суммарное количество элементов --> 4

Какого типа элементы матрицы   --> torch.int64


In [7]:
vector_tensor[1]  # Поддерживает индексное обращение

tensor(0.5000)

In [8]:
vector_tensor[:3]  # Поддерживает срезы

tensor([1.0000, 0.5000, 3.7000])

In [6]:
matrix[0][1]  # Так мы обращаемся ко второму элементу первой строки во вложенных массивах

2

In [7]:
matrix_tensor[0, 1]  # Однако к элементам тензора можно обращаться проще

tensor(2)

In [11]:
matrix_tensor[:, 0]  # Срезы так же поддерживаются, к примеру, так можно выделить первую колонку из матрицы

tensor([1, 3])

In [12]:
matrix_tensor[[0, 0, 1, 1], [0, 1, 0, 1]]  # Можно передавать список элементов для каждой из размерностей

tensor([1, 2, 3, 4])

In [8]:
matrix_tensor[[1, 1, 0, 0, 1], :]  # Дублирование не запрещено

tensor([[3, 4],
        [3, 4],
        [1, 2],
        [1, 2],
        [3, 4]])

In [14]:
# Также можно использовать булевы маски для выбора элементов
bool_mask = torch.tensor([False, True, True, False])

print(
    vector_tensor[bool_mask],  # Выбираем 2 и 3 элементы
    sep="\n\n",
)

tensor([0.5000, 3.7000])


In [15]:
# Работая с матрицами или многомерными тензорами маску можно передавать как с bool значением на каждый
#  элемент тензора, так и на только отдельные размерности
bool_mask_1 = torch.tensor([[True, False], [False, True]])
bool_mask_2 = torch.tensor([False, True])

print(
    matrix_tensor[bool_mask_1],  # Выбираем элементы (1, 1) и (2, 2)
    matrix_tensor[bool_mask_2, :],  # Выбираем только второй столбец
    matrix_tensor[:, bool_mask_2],  # Выбираем только вторую строчку
    sep="\n\n",
)

tensor([1, 4])

tensor([[3, 4]])

tensor([[2],
        [4]])


In [10]:
##
matrix_tensor[matrix_tensor % 2 == 0]

tensor([2, 4])

### 2. Как создавать тензоры

In [16]:
# Базовый конструктор
torch.tensor(
    # Передаётся объект, который нужно превратить в тензор
    [0., 1., -2., 3.],
    # Можно вручную указать какого типа должны быть элементы тензора
    #  (есть аналоги для основных типов Python и не только)
    dtype=torch.int,
)

/var/folders/dn/5x6w91b95lx6tf30sz6djy000000gn/T/ipykernel_3979/3564312110.py:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  torch.tensor(


tensor([ 0,  1, -2,  3], dtype=torch.int32)

In [17]:
# Создать тензор, состоящий из нулей с заданными размерами
torch.zeros(2, 3, dtype=torch.float)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [18]:
# Создать тензор, состоящий из единиц с заданными размерами
torch.ones(2, 3, dtype=torch.double)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [19]:
# Создать вектор с элементами от start до end с шагом step
#  (похоже на функцию range(), но может работать с нецелочисленными значениями и возвращает тензор)
torch.arange(-1, 8, 2, dtype=torch.int8)

tensor([-1,  1,  3,  5,  7], dtype=torch.int8)

In [19]:
##
torch.arange(-1, 8.5, 0.8)

tensor([-1.0000, -0.2000,  0.6000,  1.4000,  2.2000,  3.0000,  3.8000,  4.6000,
         5.4000,  6.2000,  7.0000,  7.8000])

In [20]:
# Создать вектор с элементами от start до end равномерно в количестве steps
torch.linspace(0, 10, 5, dtype=torch.float64)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000], dtype=torch.float64)

In [21]:
# Создать тензор со случайными int значениями из полуоткрытого интервала [low, high) 
torch.randint(
    -5, # low - минимальное значение
    5,  # high - 1 + максимальное значение
    (2, 3),  # size - размерности тензора
)

tensor([[-4, -2,  2],
        [ 3, -2, -2]])

In [28]:
##
torch.randint(-5, 6, (3, 4))

tensor([[ 2,  1,  4,  1],
        [-1, -4,  1,  0],
        [-5, -3, -2,  2]])

In [22]:
# Создать тензор со случайными значениями из равномерного распределения на полуинтервале [0,1)
torch.rand(1, 3, dtype=torch.float32)

tensor([[0.2532, 0.4905, 0.2012]])

In [23]:
# Создать тензор со случайными значениями из стандартного
#  нормального распредения N(0 - среднее, 1 - дисперсия)
torch.randn(2, 3, dtype=torch.float16)

tensor([[ 0.7539, -0.7134,  0.2651],
        [-0.6729, -0.1804,  0.5723]], dtype=torch.float16)

In [24]:
# Для многих конструкторов есть версия с ..._like, позволяющая создать тензор той же размерности что
#  и другой тензор, вместо прямого указания размерностей, dtype так же наследуется если явно не указать
#  обратного
print(
    f"zeros_like:\n{torch.zeros_like(matrix_tensor)}",
    f"ones_like:\n{torch.ones_like(vector_tensor, dtype=torch.bool)}",
    f"rand_like:\n{torch.rand_like(vector_tensor)}",
    f"randn_like:\n{torch.randn_like(matrix_tensor, dtype=torch.float)}",
    f"randint_like:\n{torch.randint_like(matrix_tensor, 0, 3)}",
    sep="\n\n",
)

zeros_like:
tensor([[0, 0],
        [0, 0]])

ones_like:
tensor([True, True, True, True])

rand_like:
tensor([0.9879, 0.1145, 0.6283, 0.9280])

randn_like:
tensor([[-0.5689, -1.1779],
        [ 0.6162, -0.0732]])

randint_like:
tensor([[1, 1],
        [0, 1]])


### 3. Математические операции

In [25]:
# Константа взаимодействует с любым тензором поэлементно
print(
    f"Изначальный вектор:\n{vector_tensor}",
    f"Умножение или деление вектора на константу:\n{vector_tensor * 2}",
    f"Прибавление или вычетание константы из вектора:\n{vector_tensor + 4}",
    f"Логические операции так же поддержаны:\n{vector_tensor > 0}",
    f"Возведение в степень как поэлементная операция:\n{vector_tensor ** 2}",
    f"В том числе можно и в обратную сторону:\n{2 ** vector_tensor}",
    sep="\n\n",
)

Изначальный вектор:
tensor([ 1.0000,  0.5000,  3.7000, -0.5000])

Умножение или деление вектора на константу:
tensor([ 2.0000,  1.0000,  7.4000, -1.0000])

Прибавление или вычетание константы из вектора:
tensor([5.0000, 4.5000, 7.7000, 3.5000])

Логические операции так же поддержаны:
tensor([ True,  True,  True, False])

Возведение в степень как поэлементная операция:
tensor([ 1.0000,  0.2500, 13.6900,  0.2500])

В том числе можно и в обратную сторону:
tensor([ 2.0000,  1.4142, 12.9960,  0.7071])


In [26]:
# Арифметика между тензорами одинаковой размерности
vector_tensor_2 = torch.tensor([0., 1., -0.5, -2.])

print(
    f"Изначальные вектора:\n{vector_tensor}\n{vector_tensor_2}",
    f"Сумма/разница векторов (поэлементно):\n{vector_tensor + vector_tensor_2}",
    f"Умножение/деление векторов (поэлементно):\n{vector_tensor * vector_tensor_2}",
    sep="\n\n",
)

Изначальные вектора:
tensor([ 1.0000,  0.5000,  3.7000, -0.5000])
tensor([ 0.0000,  1.0000, -0.5000, -2.0000])

Сумма/разница векторов (поэлементно):
tensor([ 1.0000,  1.5000,  3.2000, -2.5000])

Умножение/деление векторов (поэлементно):
tensor([ 0.0000,  0.5000, -1.8500,  1.0000])


In [27]:
# В PyTorch так же поддержана операция матричного умножения
matrix_tensor_1 = torch.tensor([[1, -1], [-2, 4]], dtype=torch.float)
matrix_tensor_2 = torch.tensor([[3, 1], [2, 1]], dtype=torch.float)

print(
    f"Изначальные матрицы:\n{matrix_tensor_1}\n{matrix_tensor_2}",
    f"Поэлементная сумма матриц\n{matrix_tensor_1 + matrix_tensor_2}",
    f"Обычный символ произведения даст поэлементное произведение матриц\n{matrix_tensor_1 * matrix_tensor_2}",
    (
        f"Матричное произведение двух матриц:"
        f"\n\nПервая на вторую\n{matrix_tensor_1 @ matrix_tensor_2}"
        f"\n\nВторая на первую\n{torch.mm(matrix_tensor_2, matrix_tensor_1)}"
    ),
    sep="\n\n\n",
)

Изначальные матрицы:
tensor([[ 1., -1.],
        [-2.,  4.]])
tensor([[3., 1.],
        [2., 1.]])


Поэлементная сумма матриц
tensor([[4., 0.],
        [0., 5.]])


Обычный символ произведения даст поэлементное произведение матриц
tensor([[ 3., -1.],
        [-4.,  4.]])


Матричное произведение двух матриц:

Первая на вторую
tensor([[1., 0.],
        [2., 2.]])

Вторая на первую
tensor([[1., 1.],
        [0., 2.]])


### 4. Функции тензоров

In [28]:
# Много функций для подсчёта статистик и быстрого взаимодействия, к примеру, поэлементных математических операций
print(
    f"Изначальный вектор:\n{vector_tensor}",
    f"Сумма элементов:\n{vector_tensor.sum()}",
    f"Максимальное значение:\n{vector_tensor.max()}",
    f"Минимальное значение:\n{vector_tensor.min()}",
    f"Среднее элементов:\n{vector_tensor.mean()}",
    f"Значения по модулю:\n{vector_tensor.abs()}",
    f"Округлить значения до ближайшего целого:\n{vector_tensor.round()}",
    f"Поэлементный квадратичный корень:\n{vector_tensor.sqrt()}",
    f"Поэлементный косинус:\n{vector_tensor.cos()}",
    "И многое-многое другое... Есть очень хорошая документация https://pytorch.org/docs/stable/torch.html",
    sep="\n\n",
)

Изначальный вектор:
tensor([ 1.0000,  0.5000,  3.7000, -0.5000])

Сумма элементов:
4.699999809265137

Максимальное значение:
3.700000047683716

Минимальное значение:
-0.5

Среднее элементов:
1.1749999523162842

Значения по модулю:
tensor([1.0000, 0.5000, 3.7000, 0.5000])

Округлить значения до ближайшего целого:
tensor([1., 0., 4., -0.])

Поэлементный квадратичный корень:
tensor([1.0000, 0.7071, 1.9235,    nan])

Поэлементный косинус:
tensor([ 0.5403,  0.8776, -0.8481,  0.8776])

И многое-многое другое... Есть очень хорошая документация https://pytorch.org/docs/stable/torch.html


### 5. Что ещё можно делать с тензорами

In [29]:
print(
    f"Изначальные вектора:\n{vector_tensor}\n{vector_tensor_2}",
    f"Объединять вдоль существующей оси:\n{torch.cat([vector_tensor, vector_tensor_2], dim=0)}",
    f"Объединять вдоль новой оси:\n{torch.stack([vector_tensor, vector_tensor_2], dim=0)}",
    f"Изменять размерность:\n{vector_tensor.reshape(2, 2)}",
    sep="\n\n",
)

Изначальные вектора:
tensor([ 1.0000,  0.5000,  3.7000, -0.5000])
tensor([ 0.0000,  1.0000, -0.5000, -2.0000])

Объединять вдоль существующей оси:
tensor([ 1.0000,  0.5000,  3.7000, -0.5000,  0.0000,  1.0000, -0.5000, -2.0000])

Объединять вдоль новой оси:
tensor([[ 1.0000,  0.5000,  3.7000, -0.5000],
        [ 0.0000,  1.0000, -0.5000, -2.0000]])

Изменять размерность:
tensor([[ 1.0000,  0.5000],
        [ 3.7000, -0.5000]])


In [30]:
# Почти для всех поточечных операций есть 2 версии этой операции
#  1. Cтандартная - к пр. vector_tensor.sqrt()
#     cчитает поэлементно корень и ВОЗВРАЩАЕТ НОВЫЙ тензор, но НЕ МЕНЯЕТ ОРИГИНАЛЬНЫЙ тензор
#  2. In-place - к пр. vector_tensor.sqrt_()
#     cчитает поэлементно корень и ВОЗВРАЩАЕТ НОВЫЙ тензор, и МЕНЯЕТ ОРИГИНАЛЬНЫЙ тензор
vector_tensor = torch.tensor([1, -2, 3, -4])

print(
    f"Смотрим на оригинальный вектор:\n{vector_tensor}",
    f"Применяем стандартную поэлементную функцию модуля числа:\n{vector_tensor.abs()}",
    f"Смотрим на оригинальный вектор второй раз:\n{vector_tensor}",
    f"Применяем in-place поэлементную функцию модуля числа:\n{vector_tensor.abs_()}",
    f"Смотрим на оригинальный вектор третий раз:\n{vector_tensor}",
    sep="\n\n",
)

Смотрим на оригинальный вектор:
tensor([ 1, -2,  3, -4])

Применяем стандартную поэлементную функцию модуля числа:
tensor([1, 2, 3, 4])

Смотрим на оригинальный вектор второй раз:
tensor([ 1, -2,  3, -4])

Применяем in-place поэлементную функцию модуля числа:
tensor([1, 2, 3, 4])

Смотрим на оригинальный вектор третий раз:
tensor([1, 2, 3, 4])
